version="0.0.1"

[zeus]
domain="zeus"
http-port=30100
grpc-port=30101
log-file="/var/log/zeus.log"

[mysql]
domain="localhost"
port=3306
user="root"
password="12345679"
database="zeus"

[swap-app]
server-addr='http://210.209.69.38:23103'
chain-id='58578dbca48967fd92b1344d740a74856ff11c830a7065947f110cff3cca118a'
app-id='0c9e557b2c282e737ab631de4a88764b38c2f604f6b80df1fa0cbaecec239e06dc96ec01a1c237598853fedd337d2c8ad61f637b4dd41ac7aa1341c472af238158578dbca48967fd92b1344d740a74856ff11c830a7065947f110cff3cca118a070000000000000000000000'